Update data preprocessing for Python 3
kyunghyuncho/dl4mt-material pull request #72
Opened 2017-02-20 14:53 UTC by jli05

* Update the `CODE_CENTRAL` URLs
* Update the data preprocessing code to Python 3

If you allow, I will update all the four sessions to Python 3.

2017-02-24 04:51 UTC, kyunghyuncho commented
it looks like this PR changes the preprocessing code to work only with python3. Is it possible to maintain the backward compatibility with python2?

2017-02-24 19:10 UTC, jli05 commented
I made the scripts and `.py` files Python 2/3 compatible. Now we can invoke 

```bash
PYTHON=<python_interpreter> ./setup_local_env.sh
```

2017-02-24 23:22 UTC, orhanf requested changes

2017-02-24 23:22 UTC, orhanf commented on data/build_dictionary.py
> +import pickle as pkl
@jli05 can we make it backward compatible with 

```python
try:
    import cPickle as pkl
except:
    import pickle as pkl
```

2017-02-25 12:00 UTC, jli05 commented
Done.

2017-02-27 19:54 UTC, orhanf commented
Thanks for your efforts @jli05, merging

2017-02-27 19:54 UTC, merged